### ISSUE TITLE
[FEATURE] Menu

### ISSUE THREAD

**Issue by danieleguglietti** [FutureTeam-IT/FutureAPI#6]
### Your Idea

```Markdown
Create a menu lib for paper platform.
It has to implement buttons too, with some default actions like shop buttons (buy/sell).
Should support RGB colors if possible.
Better if it uses Components from Adventure lib.
```

### Tasks

- [ ] Menu Class
- [ ] Button Interface/Abstract Class
  - [ ] Button Implementations (For its derivate)
  - [ ] Action Requirements check (like permission or exp lvl ecc.)

**Comment by danieleguglietti** [comment]
@Maxigame99 vorrei affidartela al 100% a te, se vuoi aggiungere qualcosa fallo trami un commento e valutiamo insieme, queste che ho scritto devono essere un punto di partenza.

**Comment by Maxigame99** [comment]
👍
